### ISSUE TITLE
Spanish site, where we store it?

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/jekyll#288] opened 2016-09-04 03:25 UTC
I finally understood  the process followed in PH. You want to integrate the translations in the same place or will create a special space for it?

**Comment by acrymble** [comment] 2016-09-04 08:24
This is a duplicate of #280 so let's keep the conversation in one place.

I think the important thing is that @wcaleb will determine where the lessons end up. You guys should just focus on making sure that they follow the style guidelines so that they can be integrated into the system. http://programminghistorian.org/new-lesson-workflow#writing-a-new-lesson

**Comment by acrymble** [comment] 2017-01-27 17:10
this is relevant again, as we prepare for soft launch

**Closed as completed** 2017-02-03 21:40 UTC
