### ISSUE TITLE
Missing sentence/fragment in the Editor Guidelines

### ISSUE THREAD

**Issue by fdlaramee** [programminghistorian/jekyll#1108] opened 2018-12-01 18:50 UTC
On the Editor Guidelines page, section "3) Add YAWL metadata", the **difficulty** bullet point seems to be missing a code snippet. The current text reads as follows:

> * difficulty To help readers evaluate which lessons best fit their goals and skill level, we provide “Recommended for ___ Users” information in the lesson YAML file. There are currently three tiers, which can be set with the following numerical codes: 1 (Beginning), 2 (Intermediate), 3 (Advanced). To add the difficulty level to the lesson, include the following in the YAML file:

Nothing follows the colon at the end of the paragraph.

**Comment by mdlincoln** [comment] 2018-12-05 02:08
@acrymble I think you last edited these guidelines - could you please take a look?

**Comment by mdlincoln** [comment] 2018-12-06 14:41
@acrymble @fdlaramee So when we make changes to any pages that have been translated into multiple languages, it's important to make sure those edits are also applied to the other versions of that page. 

This same addition needs to be synced to both the Spanish and French versions of this page. 

- [ ] Please open a new PR for the Spanish page.
- [ ] Add this edit to the French pages by directly committing to the `french-staging` branch

(Normally we'd make sure all the commits to change published pages are done in the same PR)

**Comment by mdlincoln** [comment] 2018-12-06 14:44
To see the guidelines for tagging reviews in the alternate languages to help review translations, make sure to check out our wiki: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#the-pull-request

**Comment by fdlaramee** [comment] 2018-12-06 14:45
@mdlincoln How would you like me to proceed? Do I just make the changes to french-staging myself (directly in that branch and not opening a new one) and do you want me to tag a Spanish-language reviewer to continue?

**Comment by acrymble** [comment] 2018-12-06 14:48
The problem is unique to the English page, as it was a typo, it wasn't
translated incorrectly.

**Comment by mdlincoln** [comment] 2018-12-06 14:51
No @acrymble, the English version now includes a code block with example, while the Spanish (and French?) versions don't

currently published english:

![](https://screenshotscdn.firefoxusercontent.com/images/4ffc91a9-0235-4d77-8526-affdfb215dbe.png)

Currently published Spanish

![](https://screenshotscdn.firefoxusercontent.com/images/fa7feb2e-927d-47a5-a4f4-98d1be756e7e.png)

**Comment by mdlincoln** [comment] 2018-12-06 14:53
And yes, [see here](https://github.com/programminghistorian/jekyll/issues/1108#issuecomment-444893167) to add the Spanish edits as a PR, and the french edits as direct commits to the `french-staging` branch

(once we've gotten `french-staging` published this all becomes much easier, as any change to an infrastructure page will have all commits to all languages in one single PR before it's approved and merged)

**Comment by fdlaramee** [comment] 2018-12-07 14:14
@mdlincoln The "see here" link you provided just loops to this page. 

I ran a PR on the branch but nothing happened because "there is nothing to compare". Probably because the update has already been committed to the English version. (My bad.) Or maybe because one of the Spanish editors intercepted the issue and ran with it?

And apparently someone beat me to the French version.

**Comment by mdlincoln** [comment] 2018-12-07 14:20
:P the "see here" pointed back to my comment where I had already said please open a new PR - sorry for the confusion :D

Did you push new commits to the branch? If so, then it should see differences and allow you to open a PR. If that's giving you problems, just create a brand new branch and put the spanish changes there.

**Comment by jenniferisasi** [comment] 2018-12-07 16:00
Hi all, 

Sorry for my confusion here, but, not sure if we want to add the edit/change that @acrymble did. 
Our guidelines in that section "Add YAML metadata to the lesson file" has more information or instructions and are a tiny bit different because it points to the translation... and for difficulty, for instance, we explain that there are three levels on the paragrah but on the block we have a "keep the original (translation)". 

In all, I can easily make the change and include the edit @acrymble did, but the English and Spanish versions are significantly different

**Comment by mdlincoln** [comment] 2018-12-07 16:46
Thanks for that explanation @jenniferisasi. However, won't you need this info for the case when an original lesson - not a translation - is begin submitted in Spanish? How does the Spanish team want to explain those cases in the editor guidelines?

**Comment by jenniferisasi** [comment] 2018-12-09 15:36
Thanks @mdlincoln and sorry for my late response! Upon reading both the editors' and authors' guidelines again, I think that we need to adjust the wording a little bit. We are mixing translation and original, or assuming that the editors are going to just drop the fields for translation - and all of us know we can just drop them, but it should be more clear. I'll take care of it.

**Comment by mdlincoln** [comment] 2018-12-10 14:12
Thank you for taking a look @jenniferisasi. I agree, as we shift to having our first lessons in languages other than English, we will also need to come up with translation guidelines for the English team! It may be worth checking in on the progress of the new Spanish lessons under review and think about timing for launching them...

**Closed as completed** 2018-12-16 22:06 UTC
Labels: Maintenance, Translation
