### ISSUE TITLE
TF-IDF lesson bug

### ISSUE THREAD

**Issue by jburnford** [programminghistorian/jekyll#1542] opened 2019-11-07 15:10 UTC
If you are reporting a problem with a lesson, please try to provide us with the following information:

- The full title of the lesson
"Analyzing Documents with TF-IDF," The Programming Historian 8 (2019), https://programminghistorian.org/en/lessons/analyzing-documents-with-tfidf.
- The system you are using (Mac, Linux, Windows)
I've reproduced the bug in Windows and Mac.
- Version numbers of the relevant software you are using
both cases using a Jupyter notebook/Python 3 Anaconda (the most up to data version installed yesterday on my Mac).
- The exact steps you took that caused the problem
The bug seems to be in this line: 
# construct a list of output file paths using the previous list of text files the relative path for tf_idf_output
output_filenames = [txt_file.replace(".txt", ".csv").replace("txt/", "tf_idf_output/") for txt_file in all_txt_files]
It returns the error: "TypeError: replace() takes 2 positional arguments but 3 were given"

I've tried to figure out what is going on and the replace code works if I switch in a simple string, but not if I try all_txt_files[1]. My Python is too rusty to guess why it is not treating the txt_file as a string in this line of code. Please let me know if you'd like me to try something new on my system or can otherwise help. I really appreciate this lesson. 

Best, Jim
jim.clifford@usask.ca

**Comment by jburnford** [comment] 2019-11-07 15:11
I just double-checked and the current anaconda release is Python 3.7.4

**Comment by ZoeLeBlanc** [comment] 2019-11-07 19:34
Thanks for catching this @jburnford. Looks like the issue is that `txt_file` is actually a Path object rather than a string, so just adding `str(txt_file)` so that the line becomes `[str(txt_file).replace(".txt", ".csv").replace("txt/", "tf_idf_output/") for txt_file in all_txt_files]` makes the code work. @mdlincoln should I go ahead and push up the fix to this code? I guess we also need to update the jupyter notebook right?

**Comment by mdlincoln** [comment] 2019-11-07 20:32
@mdlincoln yep, a PR for the lesson would be perfect, and for the notebook too.

funny how a reproducible notebook didn't catch this error 🙃  (where's a `:salt:` emoji when I need one)

**Comment by mdlincoln** [comment] 2019-11-18 14:51
Closed by #1556

**Closed as completed by mdlincoln** 2019-11-18 14:51 UTC
Labels: Maintenance, English
