### ISSUE TITLE
Community Survey Issue: Audience and Learning Paths

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/jekyll#1022] opened 2018-09-20 19:31 UTC
Through the survey, we learned a few things about who uses PH:
- less than half of survey participants are in History of any kind
- our readers are pretty confident with technology already

Several folks asked for learning paths that could expand the readership of PH to potentially more novice users while creating a link to existing more advanced pieces. Additionally, the beyond-Historian readership may also affect how we build these kinds of learning paths, if we become so inclined. 

Possibly along the same lines - participants asked for voting for new lessons and more open calls for lessons. Perhaps we could gauge interest via a poll/voting for new lessons/lesson tracks?

**Comment by drjwbaker** [comment] 2018-09-21 07:05
Interesting on audience. I remain in favour of not actively catering for non-Historians: in a way I would say that, but I think it gives us a distinctive identity - we host lessons that use tools for a clear disciplinary purpose.

On calls, this could feed into our periodic calls for Lessons We'd Like to See https://github.com/programminghistorian/jekyll/pull/1008

On tracks, this seems super hard. We do have some series - eg https://programminghistorian.org/en/lessons/intro-to-bash to https://programminghistorian.org/en/lessons/research-data-with-unix - but they aren't flagged as such on the Lesson Directory. Maybe doing that would give the impetus to draw some further connections between already published material?

**Comment by acrymble** [comment] 2018-09-21 08:42
Something for the blog? The paths change over time as new lessons are produced.

**Comment by drjwbaker** [comment] 2018-09-21 16:12
To say what?

**Comment by acrymble** [comment] 2018-09-21 16:31
As a place to publish these "paths". We've had ideas about this for years and nobody's ever written one, so this would need a champion who wanted to do it.

**Comment by drjwbaker** [comment] 2018-09-21 16:42
Right. I agree, this has floated and never been done. I'm wondering why bother blog when that effort might be better used adding a 'now you might want to go here' path to a lesson?

**Comment by acrymble** [comment] 2018-09-22 12:34
My hesitation to that is that where you want to go in 2018 isn't necessarily where you'll want to go in 2023. The logical links in these paths will, I think, change over time. Hard coding them means that you're never urged to go to a lesson that was published after the one you're reading (and its ANOTHER thing we have to go back and update from time to time). 

I think it would be far more useful to offer the equivalent of the literature review every once in a while, focusing on a particular theme, and publishing it as a dated and standalone piece of work. Like the Economic History Review does each year, but tailored to our aims: https://onlinelibrary.wiley.com/doi/abs/10.1111/1468-0289.12031

**Comment by drjwbaker** [comment] 2018-09-24 08:08
Okay. Point taken. I like the EHR model. Question for me is how do we get authors? (unless you are suggesting that we do the lit review)

**Comment by drjwbaker** [comment] 2018-10-31 12:03
Re #1034 I think this demands further discussion: perhaps at our November meet?

**Comment by drjwbaker** [comment] 2018-11-29 15:56
Not sure what to do with this. Some ideas:

- manually go through adding solid links between lessons (there is an infrastructure for this in the lesson template as @mdlincoln points out).
- consider if the issue is that new users don't know where to go. Perhaps we need a blog on 'Where to Start with PH' given that we now have such an amazing wealth of lessons.
- something else?

**Comment by alsalin** [comment] 2018-11-29 17:12
Could we setup some kind of learning paths portal under Lessons? There we could group lessons, a kind of curated list in some sort of order of difficulty, and people could follow that list. We wouldn't have to hard code links into the lessons, just keep that page updated. It being centrally located would be easier to find for newcomers as we could link to that page from anywhere, specifically the Lessons page. The problem with blog posts is that once something else comes up, they become harder to find and newcomers don't know to go to the blog for that kind of information.

**Comment by mdlincoln** [comment] 2018-11-29 18:43
Is this is a need our `category` and `activity` filters should be meeting, but aren't? We already have that functionality for grouping lessons - do we need to build a whole new thing, or just repurpose existing infrastructure that isn't doing its job?

**Comment by drjwbaker** [comment] 2018-11-30 08:22
Our various filters are great. I'm looking at our yaml setup https://programminghistorian.org/en/editor-guidelines#3-add-yaml-metadata-to-the-lesson-file and perhaps it is something as *simple* (?) as adding a new topic called something like 'Getting Started', in which we put a **very small** number of lessons that are basic building blocks (that is, most of us probably know how to do them) and (in most cases) lead into more complex lessons on the site. Perhaps:

- https://programminghistorian.org/en/lessons/introduction-and-installation
- https://programminghistorian.org/en/lessons/corpus-analysis-with-antconc
- https://programminghistorian.org/en/lessons/getting-started-with-markdown
- https://programminghistorian.org/en/lessons/building-static-sites-with-jekyll-github-pages
- https://programminghistorian.org/en/lessons/intro-to-bash
- https://programminghistorian.org/en/lessons/automated-downloading-with-wget

**Comment by acrymble** [comment] 2019-03-17 19:04
This suggestion is stalled and doesn't seem to have a champion. I propose we close it unless someone wants to take it forward.

**Comment by acrymble** [comment] 2019-06-08 07:30
I'm assigning this to @amsichani because this fits under the remit of Eduation Manager

**Comment by mdlincoln** [comment] 2019-11-07 15:55
@amsichani Do we feel this is going anywhere? Or can we close?

**Comment by jenniferisasi** [comment] 2020-01-22 15:27
Since @amsichani started work on lesson sequence on #1525, can we close this issue?

**Closed as completed** 2020-01-22 16:43 UTC
Labels: Community
