### ISSUE TITLE
Working-with-text-files python lesson

### ISSUE THREAD

**Issue by Gelmixy** [programminghistorian/jekyll#1934] opened 2020-11-20 14:25 UTC
I tried to write f.write('hello world') to a file but got an error I was trying to write a string to a binary, which didn't work. When I removed the 'b' from 'wb' I was able to write the text to the .txt file. 

- The full title of the lesson: https://programminghistorian.org/en/lessons/working-with-text-files
- The system you are using: Windows
- Version numbers of the relevant software you are using: PyCharm Community Edition 2020.02.03

- The exact steps you took that caused the problem: 
>f = open('helloworld.txt','wb')
>f.write('hello world')
>f.close()

hit run

TypeError: a bytes-like object is required, not 'str'
I think it's the same issue as ticket: #1885

**Comment by walshbr** [comment] 2020-11-20 15:30
Thanks for reporting this @Gelmixy - you're correct. This is a duplicate of #1777 (though it does overlap with #1885), which is currently being investigated by a hired bug fixer. You can check that other ticket for updates as we have them. I'll close this as it is a duplicate and we want to keep the conversation in one ticket on the issue if we can. But thank you for writing!

**Closed as completed by walshbr** 2020-11-20 15:30 UTC
