### ISSUE TITLE
Possible bug/obsolescence in Geoparsing English-Language Text with the Edinburgh Geoparser

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1953] opened 2020-12-14 00:13 UTC
I am reporting this lesson for review of a possible bug or obsolescence:

- [Geoparsing English-Language Text with the Edinburgh Geoparser](https://programminghistorian.org/en/lessons/geoparsing-text-with-edinburgh)
- Using a MacBook Pro
- I followed all the steps in the lesson; the system doesn't process texts and create output files (@JoshuaGOB also tried it)

**Comment by walshbr** [comment] 2020-12-14 13:32
What was the result it gave you? Was it just that it quietly failed and did nothing or was there an error message?

**Comment by jenniferisasi** [comment] 2020-12-14 14:11
Sorry, I should know how to report bugs properly. 

When I run the example in the lesson (text file 172172.txt in `in` folder), it works BUT I suspect it is because the output file is *already there* (you get it with the download). One doesn't notice anything, so to speak, except a javascript thing in the map later (that's another issue but not worried about it right now)

However, upon trying with another text in the `in` folder and my own text, the process just again says: 

![Screen Shot 2020-12-14 at 9 02 14 AM](https://user-images.githubusercontent.com/11022533/102090123-11318900-3deb-11eb-9223-68c4b7d08d8a.png)

And no output file is created.

**Comment by walshbr** [comment] 2020-12-15 14:06
Cool! @svmelton this seems like a good candidate for the bug fixer pipeline, if we are still doing that.

**Comment by anisa-hawes** [comment] 2021-11-25 13:51
Hello all,

I have started trying this lesson today (running macOS BigSur v.11.5.2), to see if I can better understand/reproduce the error @jenniferisasi encountered. 

I actually ran into another problem, as early as the first example command. I applied the "patch" to the `setup` file as explained, but when I ran the command an error message popped up: “lxreplace” cannot be opened because the developer cannot be verified. 

I clicked to cancel the error message, but found that this meant I was not able to move onwards through the tutorial because the `out` directory was empty. 

I tried again without re-running the "patch" this time (I was wondering if it is still needed with geoparser-1.2) but I received another error pop-up. Different this time: “lxtransduce” cannot be opened because the developer cannot be verified.

Does anyone have any ideas?

**Comment by hawc2** [comment] 2022-11-01 23:29
@anisa-hawes @jenniferisasi I took a look at this. I wonder if the updated version of the program, version 1.2, released 07/07/2021, addresses some of the problems you encountered, but also creates new ones. 

The software notes say this version "– Fixed map display; fixed timeline display; fixed installation on recent versions of MacOX; integrated top candidate option into processing; updated gazetteer lookup URL- Updated LTXML2 and RXP"

There's a few things that could be updated in this lesson (including the Patch section), and I'm struggling to get the geoparser to work consistently on Mac or for any of the commands after installation to work. I don't think this would be an easy lesson for someone from our team to fix, so what other options are available? Can we ask the author to revise the lesson?

**Comment by anisa-hawes** [comment] 2022-11-02 15:57
Dear @hawc2. Thank you for testing this. 

The steps of the maintenance workflow are outlined on out Wiki here: [Achieving Sustainability: Lesson Maintenance Workflow](https://github.com/programminghistorian/jekyll/wiki/Achieving-Sustainability%3A-Lesson-Maintenance-Workflow).

Yes, we can contact the author. I found some contact details [here](https://www.ed.ac.uk/profile/dr-beatrice-alex) and I could make initial contact, if you think that is suitable.

Or, we can move forwards from Step 3:

- Adding a warning to the lesson explaining that we are aware that some users are encountering errors with this lesson, and we're looking into a solution. Let me know if you have a suggestion
- Identifying an external practitioner to carry out an assessment. We have not yet used any budget for Lesson Maintenance in this financial year, so I think James will agree to approve us proposing a spend.  

This was one thing I wanted to speak to you about: we currently have very few practitioners on our external assessors list. It would be good if we could try to build up a small network (2-3 people), ideally across EN, FR and PT. We have Jairo who has supported Lesson Maintenance for ES.

**Comment by hawc2** [comment] 2022-11-02 16:03
I see - it's worth a shot with the author. If not, I'd do both options for step 3, as finding a practitioner may take a while and putting up a warning in the meantime is probably a safe bet. Happy to help think of external practitioners, so just ping me when you need recommendations.

**Comment by rivaquiroga** [comment] 2022-11-03 13:45
Hi everyone!
I tried the 1.2 version on Linux. Unfortunately, I got stuck in the first example: 
```
Warning: the map will be blank.  To correct this, you must set
the environment variable GEOPARSER_MAP_KEY to a valid Mapbox key
```
This warning means that the output looks like this:

![Screenshot from 2022-11-03 10-29-08](https://user-images.githubusercontent.com/31421616/199733594-9365c0ed-64d5-41ea-9c83-0bbfa4b0cbc4.png)

The lesson says nothing about getting an access token to use the Mapbox API. So I checked [their documentation](https://groups.inf.ed.ac.uk/geoparser/documentation/v1.2/html/quickstart.html#mapping). And it looks like you actually need one:

![Screenshot from 2022-11-03 10-23-54](https://user-images.githubusercontent.com/31421616/199733934-08148fc2-24ec-4a1b-8ebb-ed1ca06d8640.png)

To create an account, you must provide your credit card details (even if you only use the free tier). 

![Screenshot from 2022-11-03 10-23-09](https://user-images.githubusercontent.com/31421616/199735112-2570090e-8859-4264-b2f0-dc8dbeb82e22.png)

And that is something I will not do, so I dropped my attempt to follow this lesson. 

I am not sure this is something our lessons should ask readers to do. Having a credit card should not be a requirement to use a lesson.

**Comment by hawc2** [comment] 2022-11-03 14:03
Yes, thanks @rivaquiroga. This is what happened to me too, I was confused why Mapbox wasn't brought up in the lesson. I agree with Riva, this makes the lesson problematic, and it's probably best to see what the author thinks about how it can be improved/adapted from here

**Comment by anisa-hawes** [comment] 2022-11-03 14:20
Thank you @rivaquiroga – this is very useful.

**Comment by anisa-hawes** [comment] 2022-11-03 15:56
I've written to the author this afternoon to ask if they (or a colleague in their team) has interest in contributing to an update/adaptation of this lesson.

In my email, I've outlined the problems we've encountered and explained that we feel the requirement to provide credit card details presents a barrier to many of our readers.

**Comment by anisa-hawes** [comment] 2022-11-10 11:12
Dear all,

Good news: I've received a positive reply from the author.

Beatrice Alex explained that a change was made to the Geoparser in early 2022 which introduced Mapbox instead of Google Maps. The team at Edinburgh *think* they have now found a way to utilise Mapbox without the need to supply credit card information, and so they are hoping/planning to release a new version of the Geoparser.

The new release is likely to be ready at the end of December, or early in the new year. The author has expressed enthusiasm for updating this lesson at the same time, and I will be very happy to support them to implement the necessary changes.

In the meantime, I've prepared an alert-warning box in PR #2733 which we can apply to this lesson. I propose that I close this Issue when that alert box is in place.

I will open a new Issue when I begin working with the author to prepare and implement the updates.

**Closed as completed** 2022-11-10 15:02 UTC
Labels: Maintenance, English
