### ISSUE TITLE
Estimated lesson duration

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1526] opened 2019-10-31 18:02 UTC
Suggestion from a workshop I hosted today.
A rough estimate of how long a lesson is likely to take, so that you can gauge the time commitment of learning new skills. Could be rough (less than an hour; 2-4 hours, etc).

This is common on competing products apparently.

Assigning to @amsichani as Education manager

**Comment by amsichani** [comment] 2020-01-16 08:21
Hi all , I have been working on this , and here are a couple of suggestions from my part :

- the time commitment for each lesson could vary depending on various factors (eg student's profile/ experience level/ familiarity with the content, language fluency, learning curve etc) -->  any estimation of lesson duration will be always already a proxy. I would welcome/ suggest a small blog entry explaining the need and the logic behind this, once we decide to implement it, probably alongside #1525.
 - in terms of the actual calculation/ data: we can ask (editors or/and) reviewers to provide us an estimation of the lesson duration (I wouldn't recommend authors to provide us this info as they might be experts in the area and familiar with the procedure). Then the editor will calculate on an average lesson duration and place it in the YAML .
- (technical requirements) I would recommend to place the "estimated duration" in the same line we have the 'difficulty' info - what kind of infrastructure changes this would require (in YAML and layout level) for  @programminghistorian/technical-team ?

**Comment by mdlincoln** [comment] 2020-01-16 19:17
I like that strategy @amsichani. I think it should be straightforward for you to add another metadata field into `_layouts/lesson.html`. You'd add in HTML very similar to the published date field: https://github.com/programminghistorian/jekyll/blob/68cbfa0f141be216019dc391bb4a69fc40163e61/_layouts/lesson.html#L148-L150

One note: since this is adding a new lesson metadata field, we'd normally want to ensure in the YAML checks that the field is present. It's easy to add that check in... but then all our existing lessons would have errors because they don't have this. My gut feeling is that it would be so much work to add those in for older lessons, and it's not as critical as e.g. the `reviewers` field, that it probably doesn't make sense to turn this in to a required field. What do you think?

**Comment by acrymble** [comment] 2020-01-17 08:58
Are there other companies that do estimated durations for learning activities? Maybe we can contact them to ask them how they calculate this? It can't be too complex. There must be a system somewhere.

**Comment by drjwbaker** [comment] 2020-01-17 09:23
I know the BL Digital Scholarship team run through our lessons in groups as part of their semi-regular peer supported professional development sessions. I can ask how long they tend to set aside if you want?

**Comment by amsichani** [comment] 2020-01-22 08:44
re @acrymble 's  point: If I remember correctly, online coding courses at codeacademy are offering a percentage of the course completion (70%) and you get an estimated duration mainly on reading pieces eg medium. I have done a small research and I can't recall of an online course offering an estimated duration.

re the tech side of things @mdlincoln : I get the potential trouble caused by this addition at the YAML, and I think its a safe choice to turn this into an optional field at this point , if that is going  to be less messy for older lessons and our overall procedures. I would also suggest to apply this new field addition mainly to future lessons (or lessons currently in review process, under conditions) and to explore a selective integration to existing lessons , as it will require some extra contacts and labour from previous editors and ex-peer reviewers .

**Comment by acrymble** [comment] 2020-01-22 08:56
Apparently medium just estimates based on word count, with 265 words per minute. Maybe we can adopt something similar? Maybe with a bit of extra time built in for technical bits?

**Comment by amsichani** [comment] 2020-01-22 09:26
that's an interesting idea -however we need to take into account in our calculations that our lessons are more instructions to perform functions/tasks (usually using external software, environments, downloading and importing data etc) rather than just reading texts.

**Comment by drjwbaker** [comment] 2020-02-18 11:15
Okay, further to our email exchange, one thing about our lessons that we could do better - wrt this ticket - is to at least state when installs will take a little while.

We may not be able to say how long it takes to do the lesson as a whole (users are different), but we should be able to to say that - for example - installing a package may take a little time.

My thought here is that a user may set aside - say - 30 minutes to work on our lesson, only to find that they spend a good portion of that time on setup. If we can get in the habit of flagging such things at the start, we may help users get a sense of how long to set aside.

This may not be something we want to do retrospectively, but could be something for the editorial guidelines.

**Comment by walshbr** [comment] 2020-02-18 13:54
My read on this is similar to @amsichani and @mdlincoln - I wouldn't begin knowing how to estimate the length for any lesson I've edited or even the one I wrote, because there are too many variables: audience, discipline, software, hardware, learning speed, etc. Any number I could provide would feel pretty made up and not useful. The better thing, I think, would be to have the editor ballpark difficulty - easy, medium, hard. And we already do that as part of the publishing process. I guess a compromise position might be to just offer a sentence each on what those ballpark difficulties actually mean, but that probably would require a separate conversation.

**Comment by acrymble** [comment] 2020-02-18 14:10
I think those are fair observations @walshbr. But I worry we're focusing too much on the minutae of how, when the real question underlying this thread is how can we make our lessons page easier for potential readers to land on the skills they need. In particular, helping educators and students (as opposed to researchers who fall under the mandate of the vacant Research Impact post) to decide if a lesson is going to be useful for them and that they have the time/resources/patience to actually go through it.

A reasonable use case for our journals for an educator would be to look for lessons that could reasonably be completed by (some) students in a 1 hour workshop session, while perhaps having some students take the rest as homework. How can we help people with a pedagogical need and the restrictions of classroom time to navigate to appropriate lessons?

**Comment by drjwbaker** [comment] 2020-02-18 14:11
> A reasonable use case for our journals for an educator would be to look for lessons that could reasonably be completed by (some) students in a 1 hour workshop session, while perhaps having some students take the rest as homework. How can we help people with a pedagogical need and the restrictions of classroom time to navigate to appropriate lessons?

This lesson requires set up time is one..

**Comment by amsichani** [comment] 2020-03-02 17:51
many thanks to all for your comments and ideas so far. I am planning to work on this and #1525 in the next couple of days and I will update the relevant tickets.

**Comment by amsichani** [comment] 2020-04-13 16:47
2020-04-13  meeting https://github.com/programminghistorian/jekyll/issues/1722 we ve decided to close this ticket for now.

**Closed as completed by amsichani** 2020-04-13 16:47 UTC
Labels: Enhancement, Technical, Community
