### ISSUE TITLE
Working with Text Files in Python - Error: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by jakubow** [programminghistorian/jekyll#1900] opened 2020-09-18 16:11 UTC
Lesson Title: Working with Text Files in Python
System: Windows
Software: Komodo Edit 12, Python 3.8.5
Steps: 
I am trying to do: Creating and Writing to a Text File
I enter into Komodo: 

# file-output.py
f = open('helloworld.txt','wb')
f.write('hello world')
f.close()

I save the file as file-output.py
I "Run Python"

Returns the following error:
Traceback (most recent call last):
  File "file-output.py", line 3, in <module>
    f.write('hello world')
TypeError: a bytes-like object is required, not 'str'

**Comment by acrymble** [comment] 2020-09-18 16:29
Relevant earlier ticket: https://github.com/programminghistorian/jekyll/issues/1611 (this may be a mac vs pc problem)

**Comment by walshbr** [comment] 2020-09-18 16:32
This is a duplicate of https://github.com/programminghistorian/jekyll/issues/1777, which I think we were looking to hire a bug tester to look at?

**Comment by acrymble** [comment] 2020-09-18 16:34
Thanks @jakubow we have someone taking a look at the matter. I hope you're able to adapt the examples as you go through in the meantime.

**Closed as completed by acrymble** 2020-09-18 16:34 UTC
