### ISSUE TITLE
Issues with Getting Started with Markdown lesson 

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1528] opened 2019-11-01 14:24 UTC
I am in the middle of translating in French the following lesson: [Getting Started with Markdown](https://programminghistorian.org/en/lessons/getting-started-with-markdown) authored by @ssimpkin   

There is one tech issue in [this part ](https://programminghistorian.org/en/lessons/getting-started-with-markdown#markdown-syntax), as the URL provided in the text to display a PH lesson in the editor should rather be this one: https://github.com/programminghistorian/jekyll/blob/gh-pages/en/lessons/getting-started-with-markdown.md We can fix this easily in the PH and it concerns equally the EN and ES teams as there is already a translation in Spanish. 

More importantly (which is why I ping the author as well): StackEdit has apparently a version 5 now, instead of the v. 4 used in the lesson. The v. 4 still works but as I tried to do the exercise in the v. 5 to see if all works, I found some differences in the interface. Mainly that I do not seem to find a way to import a text from a URL, which is the basis of the exercise. Perhaps I am wrong but I would like the opinion of the author on this, as inevitably I should add a note in the translated tutorial. 

Thank you @ssimpkin @programminghistorian/english-team and @programminghistorian/spanish-team

**Comment by walshbr** [comment] 2019-11-01 14:36
Re: the link issue - I do think you want to keep to raw version of the GitHub output. Otherwise, you'll get a lot of HTML gunk that won't render correctly in the markdown editor. The issue is just the new addition of /en/ in the URL since this was published before the translations happened (I assume). So without the /en/ it gives a 404 and won't import correctly. And I think this is the link they want based on the surrounding text - 

https://raw.githubusercontent.com/programminghistorian/jekyll/gh-pages/en/lessons/intro-to-bash.md

**Comment by spapastamkou** [comment] 2019-11-01 14:49
I think you are right on this, @walshbr, thank you very much!

**Comment by mdlincoln** [comment] 2019-11-07 15:40
I don't think this issue has action items, so I'm closing it. I think further discussion about versioning can take place on the eventual ph-submissions ticket, if that's ok?

**Closed as completed by mdlincoln** 2019-11-07 15:40 UTC
Labels: Maintenance
